"""
Källkonfiguration för Ekoresiliens-scrapern.
Varje källa har en strategi: 'rss', 'ical', eller 'html'.
Lägg till nya källor här utan att ändra scraper.py.
"""

SOURCES = [
    {
        "id": "slu",
        "name": "SLU",
        "full_name": "Sveriges lantbruksuniversitet (SLU)",
        "url": "https://www.slu.se/om-slu/kalender/",
        "strategy": "html",
        "categories": ["mat", "skog", "biodiv", "agroforestry"],
        "scraper_config": {
            # BeautifulSoup selectors – uppdatera om SLU:s HTML ändras
            "event_selector": "article.event, li.event, .calendar-event, .event-item",
            "title_selector": "h2, h3, .event-title, a",
            "date_selector": "time, .event-date, .date",
            "description_selector": "p, .event-description, .preamble",
            "link_selector": "a",
        },
    },
    {
        "id": "slu_rss",
        "name": "SLU",
        "full_name": "Sveriges lantbruksuniversitet (SLU)",
        "url": "https://www.slu.se/feed/kalender/",
        "strategy": "rss",
        "categories": ["mat", "skog", "biodiv", "agroforestry"],
    },
    {
        "id": "naturvardsverket",
        "name": "NV",
        "full_name": "Naturvårdsverket",
        "url": "https://www.naturvardsverket.se/om-naturvardsverket/evenemang/",
        "strategy": "html",
        "categories": ["klimat", "biodiv", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, .list-item, li.event",
            "title_selector": "h2, h3, .title, a",
            "date_selector": "time, .date, .event-date",
            "description_selector": "p, .preamble, .intro",
            "link_selector": "a",
        },
    },
    {
        "id": "smhi",
        "name": "SMHI",
        "full_name": "SMHI",
        "url": "https://www.smhi.se/om-smhi/aktuellt/",
        "strategy": "html",
        "categories": ["klimat"],
        "scraper_config": {
            "event_selector": "article, .news-item, .event, li",
            "title_selector": "h2, h3, a, .title",
            "date_selector": "time, .date, .published",
            "description_selector": "p, .preamble, .intro",
            "link_selector": "a",
        },
    },
    {
        "id": "skogsstyrelsen",
        "name": "SKS",
        "full_name": "Skogsstyrelsen",
        "url": "https://www.skogsstyrelsen.se/kalender/",
        "strategy": "html",
        "categories": ["skog", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, .calendar-item, li",
            "title_selector": "h2, h3, .title, a",
            "date_selector": "time, .date, .event-date",
            "description_selector": "p, .preamble",
            "link_selector": "a",
        },
    },
    {
        "id": "hav",
        "name": "HaV",
        "full_name": "Havs- och vattenmyndigheten",
        "url": "https://www.havochvatten.se/om-myndigheten/kalender.html",
        "strategy": "html",
        "categories": ["vatten", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, .list-item, li",
            "title_selector": "h2, h3, a, .title",
            "date_selector": "time, .date",
            "description_selector": "p, .preamble",
            "link_selector": "a",
        },
    },
    {
        "id": "vinnova_rss",
        "name": "Vinnova",
        "full_name": "Vinnova",
        "url": "https://www.vinnova.se/nyheter/feed/",
        "strategy": "rss",
        "categories": ["samhalle", "energi"],
    },
    {
        "id": "riksantikvarieambetet",
        "name": "RAÄ",
        "full_name": "Riksantikvarieämbetet",
        "url": "https://www.raa.se/om-riksantikvarieambetet/kalender/",
        "strategy": "html",
        "categories": ["samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p",
            "link_selector": "a",
        },
    },
    {
        "id": "sva_va",
        "name": "SVA",
        "full_name": "Vetenskap & Allmänhet",
        "url": "https://v-a.se/aktiviteter/",
        "strategy": "html",
        "categories": ["samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, .activity, li",
            "title_selector": "h2, h3, a, .title",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "resurscentrum",
        "name": "RC",
        "full_name": "Resurscentrum",
        "url": "https://www.resurscentrum.se/evenemang/",
        "strategy": "html",
        "categories": ["samhalle", "energi"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p",
            "link_selector": "a",
        },
    },
    # Agroforestry och permakultur
    {
        "id": "agroforestry_sverige",
        "name": "AF",
        "full_name": "Agroforestry Sverige",
        "url": "https://agroforestrysverige.se/evenemang/",
        "strategy": "html",
        "categories": ["agroforestry", "mat", "skog"],
        "scraper_config": {
            "event_selector": "article, .event, .tribe-event, li",
            "title_selector": "h2, h3, a, .tribe-event-url",
            "date_selector": "time, .tribe-event-schedule-details, .date",
            "description_selector": "p, .tribe-events-schedule",
            "link_selector": "a",
        },
    },
    {
        "id": "permakultur_sverige",
        "name": "PF",
        "full_name": "Permakultur Sverige",
        "url": "https://www.permakultur.se/kurser/",
        "strategy": "html",
        "categories": ["skogstradgard", "agroforestry", "mat"],
        "scraper_config": {
            "event_selector": "article, .course, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
]

# Kategorimappning: nyckelord i titel/beskrivning → kategori
CATEGORY_KEYWORDS = {
    "klimat":        ["klimat", "väder", "temperatur", "co2", "utsläpp", "koldioxid", "växthus",
                      "klimatanpassning", "klimatförändring"],
    "biodiv":        ["biologisk mångfald", "biodiversitet", "arter", "naturvård", "ekosystem",
                      "pollinator", "insekt", "fågel", "däggdjur", "habititat"],
    "vatten":        ["vatten", "hav", "sjö", "vattendrag", "grundvatten", "kust", "marin",
                      "vattenkvalitet", "dagvatten", "översvämning"],
    "skog":          ["skog", "träd", "avverkning", "skogsbruk", "skogsskötsel", "hygge",
                      "kontinuitetsskogsbruk", "björk", "gran", "tall"],
    "mat":           ["jordbruk", "lantbruk", "mat", "livsmedel", "odling", "grödor", "bete",
                      "betesmark", "åker", "grönsaker", "frukt"],
    "energi":        ["energi", "sol", "vind", "vindkraft", "solenergi", "förnybar",
                      "energieffektivisering", "bioenergi", "värme"],
    "samhalle":      ["samhälle", "kommun", "region", "stadsplanering", "medborgare",
                      "demokrati", "hållbar stad", "upphandling"],
    "policy":        ["lagstiftning", "lag", "förordning", "direktiv", "eu", "policy",
                      "reglering", "tillstånd", "myndighet"],
    "agroforestry":  ["agroforestry", "alléodling", "silvopastoral", "silvoarable",
                      "träd på åker", "lövträd", "trädrader"],
    "skogstradgard": ["skogsträdgård", "food forest", "permakultur", "permaculture",
                      "ätbar skog", "guild", "succession", "flerskiktat"],
}
