"""
Källkonfiguration för Ekoresiliens-scrapern.
Varje källa har en strategi: 'rss', 'ical', eller 'html'.
Lägg till nya källor här utan att ändra scraper.py.
"""

SOURCES = [
    {
        "id": "slu",
        "name": "SLU",
        "full_name": "Sveriges lantbruksuniversitet (SLU)",
        "url": "https://www.slu.se/om-slu/kalender/",
        "strategy": "html",
        "categories": ["mat", "skog", "biodiv", "agroforestry"],
        "scraper_config": {
            # BeautifulSoup selectors – uppdatera om SLU:s HTML ändras
            "event_selector": "article.event, li.event, .calendar-event, .event-item",
            "title_selector": "h2, h3, .event-title, a",
            "date_selector": "time, .event-date, .date",
            "description_selector": "p, .event-description, .preamble",
            "link_selector": "a",
        },
    },
    {
        "id": "slu_rss",
        "name": "SLU",
        "full_name": "Sveriges lantbruksuniversitet (SLU)",
        "url": "https://www.slu.se/om-slu/organisation/framtidsplattformar/slu-urban-futures/uf-kalender/",
        "strategy": "rss",
        "categories": ["mat", "skog", "biodiv", "agroforestry"],
    },
    {
        "id": "smhi",
        "name": "SMHI",
        "full_name": "SMHI",
        "url": "https://www.smhi.se/om-smhi/aktuellt/",
        "strategy": "html",
        "categories": ["klimat"],
        "scraper_config": {
            "event_selector": "article, .news-item, .event, li",
            "title_selector": "h2, h3, a, .title",
            "date_selector": "time, .date, .published",
            "description_selector": "p, .preamble, .intro",
            "link_selector": "a",
        },
    },
    {
        "id": "vinnova_rss",
        "name": "Vinnova",
        "full_name": "Vinnova",
        "url": "https://www.vinnova.se/nyheter/feed/",
        "strategy": "rss",
        "categories": ["samhalle", "energi"],
    },
    {
        "id": "riksantikvarieambetet",
        "name": "RAÄ",
        "full_name": "Riksantikvarieämbetet",
        "url": "https://www.raa.se/om-riksantikvarieambetet/kalender/",
        "strategy": "html",
        "categories": ["samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p",
            "link_selector": "a",
        },
    },
    {
        "id": "sva_va",
        "name": "SVA",
        "full_name": "Vetenskap & Allmänhet",
        "url": "https://v-a.se/aktiviteter/",
        "strategy": "html",
        "categories": ["samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, .activity, li",
            "title_selector": "h2, h3, a, .title",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "resurscentrum",
        "name": "RC",
        "full_name": "Resurscentrum",
        "url": "https://www.resurscentrum.se/evenemang/",
        "strategy": "html",
        "categories": ["samhalle", "energi"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p",
            "link_selector": "a",
        },
    },
    # Agroforestry och permakultur
    {
        "id": "agroforestry_sverige",
        "name": "AF",
        "full_name": "Agroforestry Sverige",
        "url": "https://agroforestrysverige.se/evenemang/",
        "strategy": "html",
        "categories": ["agroforestry", "mat", "skog"],
        "scraper_config": {
            "event_selector": "article, .event, .tribe-event, li",
            "title_selector": "h2, h3, a, .tribe-event-url",
            "date_selector": "time, .tribe-event-schedule-details, .date",
            "description_selector": "p, .tribe-events-schedule",
            "link_selector": "a",
        },
    },
    {
        "id": "permakultur_sverige",
        "name": "PF",
        "full_name": "Permakultur Sverige",
        "url": "https://www.permakultur.se/kurser/",
        "strategy": "html",
        "categories": ["skogstradgard", "agroforestry", "mat"],
        "scraper_config": {
            "event_selector": "article, .course, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    # Nya källor för webbinarier och evenemang
    {
        "id": "region_vg",
        "name": "VGR",
        "full_name": "Västra Götalandsregionen",
        "url": "https://regionkalender.vgregion.se/sv/",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, .calendar-event, li",
            "title_selector": "h2, h3, a, .event-title",
            "date_selector": "time, .event-date, .date",
            "description_selector": "p, .event-description, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "movium_slu",
        "name": "MOVIUM",
        "full_name": "SLU MOVIUM",
        "url": "https://movium.slu.se/kalendarium/",
        "strategy": "html",
        "categories": ["samhalle", "biodiv", "skog"],
        "scraper_config": {
            "event_selector": "article, .event, .post, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date, .published",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "slu_urban",
        "name": "SLU Urban",
        "full_name": "SLU Urbana landskap",
        "url": "https://www.slu.se/om-slu/organisation/framtidsplattformar/slu-urban-futures/se-lyssna-folj/webbinarier/motesplats-urbana-landskap/",
        "strategy": "html",
        "categories": ["samhalle", "biodiv", "mat"],
        "scraper_config": {
            "event_selector": "article, .event, .webinar, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "boverket_webinar",
        "name": "BV Webinar",
        "full_name": "Boverket Webbinarier",
        "url": "https://www.boverket.se/sv/samhallsplanering/livsvillkor-och-utanforskap/kunskapsstod/webbinarieserie/",
        "strategy": "html",
        "categories": ["samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, .webinar, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "boverket_kalender",
        "name": "BV Kalender",
        "full_name": "Boverket Kalender",
        "url": "https://www.boverket.se/sv/hallbar-stad/kalender/",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "omstalningsfonden",
        "name": "ÖF",
        "full_name": "Omställningsfonden",
        "url": "https://www.omstallningsfonden.se/sv/om-oss/Kalendarium/",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "energi"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "nv_kalendarium",
        "name": "NV Kal",
        "full_name": "Naturvårdsverket Kalendarium",
        "url": "https://www.naturvardsverket.se/om-oss/aktuellt/kalendarium/?q=kalendarium",
        "strategy": "html",
        "categories": ["klimat", "biodiv", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "aktuell_hallbarhet",
        "name": "AH",
        "full_name": "Aktuell Hållbarhet",
        "url": "https://www.aktuellhallbarhet.se/event/",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "energi"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    # Nya källor för miljö och hållbarhet
    {
        "id": "treesforme",
        "name": "Trees for Me",
        "full_name": "Trees for Me",
        "url": "https://treesforme.se/sv/kalendarium/",
        "strategy": "html",
        "categories": ["biodiv", "skog", "mat"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "svenskt_vatten",
        "name": "SV",
        "full_name": "Svenskt Vatten",
        "url": "https://www.svensktvatten.se/utbildning-och-konferens/konferenser-och-evenemang/",
        "strategy": "html",
        "categories": ["vatten", "samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "klimat2030",
        "name": "Klimat 2030",
        "full_name": "Klimat 2030",
        "url": "https://klimat2030.se/category/evenemang/",
        "strategy": "html",
        "categories": ["klimat", "samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "business_biodiversity",
        "name": "B&B",
        "full_name": "Business & Biodiversity",
        "url": "https://www.businessandbiodiversity.se/program",
        "strategy": "html",
        "categories": ["biodiv", "policy", "samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    # Länsstyrelsens kalendrar för olika regioner
    {
        "id": "ls_skane",
        "name": "LS Skåne",
        "full_name": "Länsstyrelsen Skåne",
        "url": "https://www.lansstyrelsen.se/skane/om-oss/kalender/kalenderhandelser---skane/",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_vgotaland",
        "name": "LS VG",
        "full_name": "Länsstyrelsen Västra Götaland",
        "url": "https://www.lansstyrelsen.se/vastra-gotaland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_blekinge",
        "name": "LS Blekinge",
        "full_name": "Länsstyrelsen Blekinge",
        "url": "https://www.lansstyrelsen.se/blekinge/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_dalarna",
        "name": "LS Dalarna",
        "full_name": "Länsstyrelsen Dalarna",
        "url": "https://www.lansstyrelsen.se/dalarna/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_gotland",
        "name": "LS Gotland",
        "full_name": "Länsstyrelsen Gotland",
        "url": "https://www.lansstyrelsen.se/gotland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_gavleborg",
        "name": "LS Gävleborg",
        "full_name": "Länsstyrelsen Gävleborg",
        "url": "https://www.lansstyrelsen.se/gavleborg/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_halland",
        "name": "LS Halland",
        "full_name": "Länsstyrelsen Halland",
        "url": "https://www.lansstyrelsen.se/halland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_jamtland",
        "name": "LS Jämtland",
        "full_name": "Länsstyrelsen Jämtland",
        "url": "https://www.lansstyrelsen.se/jamtland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_jonkoping",
        "name": "LS Jönköping",
        "full_name": "Länsstyrelsen Jönköping",
        "url": "https://www.lansstyrelsen.se/jonkoping/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_kalmar",
        "name": "LS Kalmar",
        "full_name": "Länsstyrelsen Kalmar",
        "url": "https://www.lansstyrelsen.se/kalmar/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_kronoberg",
        "name": "LS Kronoberg",
        "full_name": "Länsstyrelsen Kronoberg",
        "url": "https://www.lansstyrelsen.se/kronoberg/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_norrbotten",
        "name": "LS Norrbotten",
        "full_name": "Länsstyrelsen Norrbotten",
        "url": "https://www.lansstyrelsen.se/norrbotten/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_stockholm",
        "name": "LS Stockholm",
        "full_name": "Länsstyrelsen Stockholm",
        "url": "https://www.lansstyrelsen.se/stockholm/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_sodermanland",
        "name": "LS Södermanland",
        "full_name": "Länsstyrelsen Södermanland",
        "url": "https://www.lansstyrelsen.se/sodermanland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_uppsala",
        "name": "LS Uppsala",
        "full_name": "Länsstyrelsen Uppsala",
        "url": "https://www.lansstyrelsen.se/uppsala/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_varmland",
        "name": "LS Värmland",
        "full_name": "Länsstyrelsen Värmland",
        "url": "https://www.lansstyrelsen.se/varmland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_vastmanland",
        "name": "LS Västmanland",
        "full_name": "Länsstyrelsen Västmanland",
        "url": "https://www.lansstyrelsen.se/vastmanland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_orebro",
        "name": "LS Örebro",
        "full_name": "Länsstyrelsen Örebro",
        "url": "https://www.lansstyrelsen.se/orebro/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ls_ostergotland",
        "name": "LS Östergötland",
        "full_name": "Länsstyrelsen Östergötland",
        "url": "https://www.lansstyrelsen.se/ostergotland/om-oss/kalender.html",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "biodiv"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    # Ytterligare miljö- och hållbarhetskällor
    {
        "id": "energimyndigheten",
        "name": "EM",
        "full_name": "Energimyndigheten",
        "url": "https://www.energimyndigheten.se/om-oss/press-och-kanaler/kalender/",
        "strategy": "html",
        "categories": ["energi", "klimat", "samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ekocentrum",
        "name": "Ekocentrum",
        "full_name": "Ekocentrum",
        "url": "https://www.ekocentrum.se/kalendarium-start/",
        "strategy": "html",
        "categories": ["biodiv", "mat", "samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "wsp",
        "name": "WSP",
        "full_name": "WSP",
        "url": "https://www.wsp.com/sv-se/event",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "mcf",
        "name": "MCF",
        "full_name": "Miljöcenter Framtid",
        "url": "https://www.mcf.se/sv/aktuellt/kalender/",
        "strategy": "html",
        "categories": ["biodiv", "klimat", "samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ri",
        "name": "RI",
        "full_name": "Ragnar Itterström Institutet",
        "url": "https://www.ri.se/sv/nyheter/kalendarium",
        "strategy": "html",
        "categories": ["klimat", "samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "lrf",
        "name": "LRF",
        "full_name": "Lantbrukarnas Riksförbund",
        "url": "https://www.lrf.se/kalender/",
        "strategy": "html",
        "categories": ["mat", "skog", "klimat"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "klimatriksdagen",
        "name": "KR",
        "full_name": "Klimatriksdagen",
        "url": "https://klimatriksdagen.se/aktuellt/",
        "strategy": "html",
        "categories": ["klimat", "samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "sgi",
        "name": "SGI",
        "full_name": "Statens geotekniska institut",
        "url": "https://www.sgi.se/om-sgi/om-myndigheten/kurser-och-konferenser/webbinarier",
        "strategy": "html",
        "categories": ["samhalle", "klimat", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "ekologigruppen",
        "name": "Ekologigruppen",
        "full_name": "Ekologigruppen",
        "url": "https://www.ekologigruppen.se/blogg/webinarier/",
        "strategy": "html",
        "categories": ["biodiv", "mat", "samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "klimatanpassning_tst",
        "name": "KA",
        "full_name": "Klimatanpassning Sverige",
        "url": "https://www-tst.klimatanpassning.se/kalender",
        "strategy": "html",
        "categories": ["klimat", "samhalle", "policy"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
    {
        "id": "holmafolkhogskola",
        "name": "HFH",
        "full_name": "Holma Folkhögskola",
        "url": "https://www.holmafolkhogskola.se/oppet-program/",
        "strategy": "html",
        "categories": ["mat", "biodiv", "samhalle"],
        "scraper_config": {
            "event_selector": "article, .event, li",
            "title_selector": "h2, h3, a",
            "date_selector": "time, .date",
            "description_selector": "p, .excerpt",
            "link_selector": "a",
        },
    },
]

# Kategorimappning: nyckelord i titel/beskrivning → kategori
CATEGORY_KEYWORDS = {
    "klimat":        ["klimat", "väder", "temperatur", "co2", "utsläpp", "koldioxid", "växthus",
                      "klimatanpassning", "klimatförändring"],
    "biodiv":        ["biologisk mångfald", "biodiversitet", "arter", "naturvård", "ekosystem",
                      "pollinator", "insekt", "fågel", "däggdjur", "habititat"],
    "vatten":        ["vatten", "hav", "sjö", "vattendrag", "grundvatten", "kust", "marin",
                      "vattenkvalitet", "dagvatten", "översvämning"],
    "skog":          ["skog", "träd", "avverkning", "skogsbruk", "skogsskötsel", "hygge",
                      "kontinuitetsskogsbruk", "björk", "gran", "tall"],
    "mat":           ["jordbruk", "lantbruk", "mat", "livsmedel", "odling", "grödor", "bete",
                      "betesmark", "åker", "grönsaker", "frukt"],
    "energi":        ["energi", "sol", "vind", "vindkraft", "solenergi", "förnybar",
                      "energieffektivisering", "bioenergi", "värme"],
    "samhalle":      ["samhälle", "kommun", "region", "stadsplanering", "medborgare",
                      "demokrati", "hållbar stad", "upphandling"],
    "policy":        ["lagstiftning", "lag", "förordning", "direktiv", "eu", "policy",
                      "reglering", "tillstånd", "myndighet"],
    "agroforestry":  ["agroforestry", "alléodling", "silvopastoral", "silvoarable",
                      "träd på åker", "lövträd", "trädrader"],
    "skogstradgard": ["skogsträdgård", "food forest", "permakultur", "permaculture",
                      "ätbar skog", "guild", "succession", "flerskiktat"],
}
